package com.medison.pacs.series.domain;

import lombok.Getter;

import javax.persistence.*;

@Getter
@IdClass(SeriesId.class)
@Table(name = "SERIESTAB", schema = "PACSPLUS")
@Entity
public class Series {
 @Id
 private Long studykey;	//number(38,0)
 @Id
 private Long serieskey;//	number(38,0)
 private String studyinsuid;	//varchar2(64 byte)
 private String seriesinsuid;	//varchar2(64 byte)
 private Long seriesnum;	//number(38,0)
 private Long seriescurseqnum;	//number(38,0)
 private String studyid;	//varchar2(64 byte)
 private String modality;	//varchar2(16 byte)
 private String  bodypart;	//varchar2(256 byte)
 private String seriesdesc;	//varchar2(256 byte)
 private String protocolname; //varchar2(64 byte)
 private String viewposition;	//varchar2(255 byte)
 private String laterality;	//varchar2(64 byte)
 private String comments;	//varchar2(255 byte)
 private Long imagecnt;	//number(38,0)
 private Long moviecnt;	//number(38,0)
 private String seriestype;	//varchar2(64 byte)
 private Long verifyflag;	//number(38,0)
 private Long delflag;	//number(38,0)
 private String seriesdate;	//varchar2(8 byte)
 private String seriestime;	//varchar2(14 byte)
 private String insertdate;	//varchar2(8 byte)
 private String inserttime;	//varchar2(8 byte)
 private Long hospitalid;	//number(38,0)
 private String performingphysicianname;	//varchar2(64 byte)
 private String operatorsname;	//varchar2(64 byte)
 private String patposition;	//varchar2(64 byte)
 private String anatomicalorientationtype;	//varchar2(64 byte)
 private String manufacturer;	//varchar2(64 byte)
 private String institutionname;	//varchar2(256 byte)
 private String stationname;	//varchar2(64 byte)
 private String institutionaldepartmentname;	//varchar2(64 byte)
 private String manumodelname;	//varchar2(64 byte)
 private Long nonimagecount;	//number
 private Long filesize;	//number
 private String inserted;	//varchar2(14 byte)
 private String updated;	//varchar2(14 byte)
 private Long reserved1;	//number(38,0)
 private Long reserved2;	//number(38,0)
 private Long reserved3;	//number(38,0)
 private String reserved4;	//varchar2(255 byte)
 private String reserved5;	//varchar2(255 byte)
 private String reserved6;	//varchar2(255 byte)
 private String reserved7;	//varchar2(255 byte)
 private String reserved8;	//varchar2(255 byte)
 private String reserved9;	//varchar2(255 byte)
 private String reserved10;	//varchar2(255 byte)
// private String anatomicalOrientationType;	//varchar2(255 char)
// private String bodyPart;	//varchar2(255 char)
// private String insertDate;	//varchar2(255 char)
// private String insertTime;	//varchar2(255 char)
// private String institutionName;	//varchar2(255 char)
// private String institutionalDepartmentName;	//varchar2(255 char)
// private String manuModelName;	//varchar2(255 char)
// private String operatorsName;	//varchar2(255 char)
// private String patPosition;	//varchar2(255 char)
// private String performingPhysicianName;	//varchar2(255 char)
// private String protocolName;	//varchar2(255 char)
// private String seriesDate;	//varchar2(255 char)
// private String seriesDesc;	//varchar2(255 char)
// private String seriesInsUid;	//varchar2(255 char)
// private String seriesTime;	//varchar2(255 char)
// private String seriesType;	//varchar2(255 char)
// private String stationName;	//varchar2(255 char)
// private String studyId;	//varchar2(255 char)
// private String studyInsUid;	//varchar2(255 char)
// private String viewPosition;	//varchar2(255 char)
// private Long seriesKey;	//number(19,2)
// private String manuModelname;	//varchar2(255 char)
}
